/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 16 13:53:15 GMT 2022
 */

package org.apache.tika.sax;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.tika.sax.TaggedSAXException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.xml.sax.SAXException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TaggedSAXException_ESTest extends TaggedSAXException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SAXException sAXException0 = new SAXException();
      TaggedSAXException taggedSAXException0 = new TaggedSAXException(sAXException0, sAXException0);
      Object object0 = taggedSAXException0.getTag();
      assertSame(sAXException0, object0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SAXException sAXException0 = new SAXException((String) null, (Exception) null);
      TaggedSAXException taggedSAXException0 = new TaggedSAXException(sAXException0, (Object) null);
      Object object0 = taggedSAXException0.getTag();
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SAXException sAXException0 = new SAXException();
      TaggedSAXException taggedSAXException0 = new TaggedSAXException(sAXException0, sAXException0);
      SAXException sAXException1 = taggedSAXException0.getCause();
      assertSame(sAXException0, sAXException1);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SAXException sAXException0 = new SAXException((Exception) null);
      TaggedSAXException taggedSAXException0 = null;
      try {
        taggedSAXException0 = new TaggedSAXException((SAXException) null, sAXException0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tika.sax.TaggedSAXException", e);
      }
  }
}
